### ISSUE TITLE
Suggestion: ProtoConnection#equals() should be able to compare whether two ProtoConnections.

### ISSUE THREAD

**Issue by Klyser8** [MrNavaStar/ProtoWeaver#88]
Not completely sure how to word this, I talked about it with the developer on Discord.
It would be neat if two instances of ProtoConnection could be checked for equality through the .equals() method.
Particularly useful to ensure that data is not being forwarded to the same connection which sent it in the first place.

**Comment by MrNavaStar** [comment]
Should be resolved in ProtoWeaver 1.3.11
